# Generated by Django 5.2.11 on 2026-02-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramadan_day', models.PositiveIntegerField(unique=True, verbose_name='Ramadan Day Number')),
                ('islamic_date', models.CharField(max_length=100, verbose_name='Islamic Date (e.g. 1 Ramadan 1447)')),
                ('gregorian_date', models.DateField(verbose_name='Gregorian Date')),
                ('day_name_en', models.CharField(max_length=20, verbose_name='Day Name (English)')),
                ('day_name_ur', models.CharField(blank=True, max_length=50, verbose_name='Day Name (Urdu)')),
                ('day_name_hi', models.CharField(blank=True, max_length=50, verbose_name='Day Name (Hindi)')),
                ('sehri_time', models.TimeField(verbose_name='Sehri Time (End)')),
                ('iftar_time', models.TimeField(verbose_name='Iftar Time')),
                ('dua_text', models.TextField(blank=True, verbose_name='Dua / Quote (Optional)')),
                ('dua_translation', models.TextField(blank=True, verbose_name='Dua Translation (Optional)')),
                ('organization_name', models.CharField(blank=True, default='Ramadan Timetable 1447 AH', max_length=200)),
                ('location', models.CharField(blank=True, default='India', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ramadan Day',
                'verbose_name_plural': 'Ramadan Days',
                'ordering': ['ramadan_day'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Ramadan Timetable 1447 AH', max_length=200)),
                ('location', models.CharField(default='India', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hijri_year', models.CharField(default='1447', max_length=10)),
                ('tagline', models.CharField(blank=True, default='رمضان مبارک', max_length=300)),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('social_handle', models.CharField(blank=True, default='#ramadanmubarak', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
